### ISSUE TITLE
Vue-mq crash whole app on ipad iOS 9.3.5

### ISSUE THREAD

**Issue by JordanQui** [AlexandreBonaventure/vue-mq#6] opened 2018-03-04 14:25 UTC
[Error] TypeError: Object.values is not a function. (In 'Object.values(t)', 'Object.values' is undefined)
	(anonymous function) (vendor.bb871968581eb32b7779.js:1:262533)
	install (vendor.bb871968581eb32b7779.js:1:262685)
	use (vendor.bb871968581eb32b7779.js:1:173054)
	NHnr (app.9b13ddd7c0531c02fe13.js:1:111824)
	o (manifest.b2235280efe91100e06a.js:1:415)
	webpackJsonp (manifest.b2235280efe91100e06a.js:1:286)
	Global Code (app.9b13ddd7c0531c02fe13.js:1)

Hello seems vue-mq is crashing app content injection 

Thanks a lot for this Wonderfull plugin

**Comment by AlexandreBonaventure** [comment] 2018-03-04 23:24
Thanks for the report, the issue is related to #3.
This will be fixed in the next release

**Closed** 2018-03-04 23:28 UTC
